export const SAVE_INFOS = 'SAVE_INFOS';
export const SAVE_PLAN = 'SAVE_PLAN';
export const SAVE_ADDITTIONS = 'SAVE_ADDITTIONS';
export const CALCULATION_VALUES = 'CALCULATION_VALUES';
export const FINISH_REGISTER = 'FINISH_REGISTER';
